# Generated by Django 2.2 on 2021-05-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emperor', '0002_song_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.FileField(upload_to='img'),
        ),
    ]
