# Generated by Django 2.2 on 2021-05-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emperor', '0003_auto_20210529_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='movie',
        ),
    ]
